/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as DiagnosticsIndexRouteImport } from './routes/diagnostics.index'
import { Route as DiagnosticsTestSlugRouteImport } from './routes/diagnostics.$testSlug'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsIndexRoute = DiagnosticsIndexRouteImport.update({
  id: '/diagnostics/',
  path: '/diagnostics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsTestSlugRoute = DiagnosticsTestSlugRouteImport.update({
  id: '/diagnostics/$testSlug',
  path: '/diagnostics/$testSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/diagnostics/$testSlug': typeof DiagnosticsTestSlugRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/diagnostics/$testSlug': typeof DiagnosticsTestSlugRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/blog': typeof BlogIndexRoute
  '/careers': typeof CareersIndexRoute
  '/diagnostics': typeof DiagnosticsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/diagnostics/$testSlug': typeof DiagnosticsTestSlugRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/diagnostics/$testSlug'
    | '/doctors/$doctorId'
    | '/services/$serviceSlug'
    | '/blog/'
    | '/careers/'
    | '/diagnostics/'
    | '/doctors/'
    | '/portal/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/diagnostics/$testSlug'
    | '/doctors/$doctorId'
    | '/services/$serviceSlug'
    | '/blog'
    | '/careers'
    | '/diagnostics'
    | '/doctors'
    | '/portal'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/diagnostics/$testSlug'
    | '/doctors/$doctorId'
    | '/services/$serviceSlug'
    | '/blog/'
    | '/careers/'
    | '/diagnostics/'
    | '/doctors/'
    | '/portal/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  InsuranceRoute: typeof InsuranceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  DiagnosticsTestSlugRoute: typeof DiagnosticsTestSlugRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  DiagnosticsIndexRoute: typeof DiagnosticsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/': {
      id: '/diagnostics/'
      path: '/diagnostics'
      fullPath: '/diagnostics/'
      preLoaderRoute: typeof DiagnosticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/$testSlug': {
      id: '/diagnostics/$testSlug'
      path: '/diagnostics/$testSlug'
      fullPath: '/diagnostics/$testSlug'
      preLoaderRoute: typeof DiagnosticsTestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AppointmentsRoute: AppointmentsRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  InsuranceRoute: InsuranceRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  DiagnosticsTestSlugRoute: DiagnosticsTestSlugRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  DiagnosticsIndexRoute: DiagnosticsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
